/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.9.0.99.2 */
/* Module Version: 5.4 */
/* Fri Jan 25 15:56:15 2019 */

/* parameterized module instance */
rom __ (.Address( ), .OutClock( ), .OutClockEn( ), .Reset( ), .Q( ));
