/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.9.0.99.2 */
/* Module Version: 5.7 */
/* Fri Jan 25 14:10:49 2019 */

/* parameterized module instance */
pll __ (.CLKI( ), .CLKOP( ));
