/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.9.0.99.2 */
/* Module Version: 5.7 */
/* Mon Jul 03 15:06:13 2017 */

/* parameterized module instance */
pll_mxo2 __ (.CLKI( ), .CLKOP( ));
